server:
  port: ${SERVER_PORT:5000}
  address: 0.0.0.0
  tomcat:
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB

spring:
  mail:
    host: ${STMP_HOST}
    port:  ${STMP_PORT}
    username:  ${STMP_USER}
    password:  ${STMP_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jmx:
    enabled: false
  main:
    allow-circular-references: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    database-platform: ${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: ${SHOW_SQL:false}
        format_sql: ${FORMAT_SQL:false}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
      enabled: true

logging:
  level:
    org.springframework.security: warn
    org.springframework.web.socket: trace

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

app:
  cors:
    allowed-origins:
      - http://localhost:3033
      - http://localhost:3000
      - http://localhost:5000
      - https://lacy-restaurant.vercel.app